name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests

      - name: Build package
        run: |
          rm -fr dist/*
          python -m build

      - name: Publish to TestPyPI
        if: contains(github.ref, 'dev')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ !contains(github.ref, 'dev') }}
        uses: pypa/gh-action-pypi-publish@release/v1